### ISSUE TITLE
Create a Home Page

### ISSUE THREAD

**Issue by Exter-dg** [Exter-dg/CovID#14]
Currently, the site has no home page. A proper homepage that has links to different sections of the site will be useful.
The page should have -

- [ ] Link to Admin Register and Login page
- [ ] Link to User Register and Login page (still under development)
- [ ] Link to the dashboard (maybe some details from the dashboard to display)
- [ ] Optional - If the design permits, we can even include a table that users can use to see available centres and slots (this will be included in the user module and the logic can be added later on)

Make sure, this follows the same design principles (from startbootstrap, refer various template pages available in the repository)

**Comment by khushi2912** [comment]
I want to work on this issue. Can you assign this to me?
