### ISSUE TITLE
Add Toolbar/Home Page button on Login/Register pages

### ISSUE THREAD

**Issue by Exter-dg** [Exter-dg/CovID#16]
The Login, as well as register pages, have no way to navigate back to the home page.

- [x] Add a toolbar/homepage button in the `admin_login.html`
- [x] Add a toolbar/homepage button in the `admin_register.php`

**Comment by everly-gif** [comment]
I would like to work on this issue
Please assign it to me

**Comment by everly-gif** [comment]
I have fixed the issue , please let me know your suggestions or if you would like any other changes.
Thanks @Exter-dg

**Comment by Exter-dg** [comment]
> I have fixed the issue , please let me know your suggestions or if you would like any other changes. Thanks @Exter-dg

The changes look fine, I have merged your PR and closing this issue.
