### ISSUE TITLE
Fix logout button in admin pages

### ISSUE THREAD

**Issue by Exter-dg** [Exter-dg/CovID#17]
Currently, when the admin clicks on logout, the site redirects to the `login.html` file which is a template file just for reference (as mentioned in the [README.md](https://github.com/Exter-dg/CovID/blob/master/README.md).
The ideal behaviour is that the page should call `admin-logout.php` which will unset session variables and logout admin.

Files where changes are required:
- `admin-home.php`
- `admin-centre.php`
- `admin-approve.php`
- `admin-slots.php`

**Comment by khushi2912** [comment]
I want to work on this issue. Please assign it to me.
